Ballerina-Org/ballerina

- .github/workflows/ci.yaml
- .vscode/settings.json
- backend/apps/ballerina-runtime/ballerina-runtime.fsproj
- backend/apps/ballerina-runtime/packages.lock.json
- backend/libraries/ballerina-core/ballerina-core.fsproj
- backend/libraries/ballerina-core/packages.lock.json
- todo.md
On each push ballerina-runtime is compiled for all runtimes.
A release is only created when pushing a tag
> ci: release pipeline

- .vscode/extensions.json
- backend/libraries/ballerina-core-go/ballerina_test/option_test.go
- backend/libraries/ballerina-core-go/go.mod
- backend/libraries/ballerina-core-go/go.sum
No functionality change, only added tests to document the current behaviour
> test: go optional serialization

- .github/workflows/ci.yaml
- backend/libraries/ballerina-core-go/error.go
- backend/libraries/ballerina-core-go/range.go
- backend/libraries/ballerina-core-go/unit.go
CI intentionally fails on first commit (to show that the check is correct)
> ci: check Go formatting

- backend/libraries/ballerina-core-go/sum.go
Per conversation earlier today
> update Sum generic

- backend/libraries/ballerina-core-go/ballerina_test/sum_test.go
- backend/libraries/ballerina-core-go/sum.go
- frontend/libraries/ballerina-core/src/forms/domains/parser/domains/built-ins/state.ts
This addresses the issue of TS needing to know how to create Go's zero-values
> fix: better Sum seralization (not relying on products)

- backend/libraries/ballerina-core-go/ballerina_test/option_test.go
- backend/libraries/ballerina-core-go/identity.go
- backend/libraries/ballerina-core-go/option.go
This will require changes to TS serialization
> feat: implement optional with Sum

- backend/libraries/ballerina-core-go/ballerina_test/option_test.go
- backend/libraries/ballerina-core-go/identity.go
- backend/libraries/ballerina-core-go/option.go
Reverts giuseppemag/ballerina#118
> Revert "feat: implement optional with Sum"

- backend/libraries/ballerina-core-go/ballerina_test/option_test.go
- backend/libraries/ballerina-core-go/option.go
- backend/libraries/ballerina-core-go/sum.go
All of this stuff needs to be added @giuseppemag
```go
func Map[T any, O any](value Value[T], fn func(T) O) Value[O] {
if value.isSet {
return Just(fn(value.value))
}
return None[O]()
}
func MapWithError[T any, O any](value Value[T], fn func(T) (O, error)) (Value[O], error) {
if value.isSet {
result, err := fn(value.value)
if err != nil {
return None[O](), err
}
return Just(result), nil
}
return None[O](), nil
}
// Foldable (catamorphism) properties
func Fold[T any, O any](value Value[T], fn func(value T) O, orElse func() O) O {
if value.isSet {
return fn(value.value)
}
return orElse()
}
func FoldWithError[T any, O any](value Value[T], fn func(value T) (O, error), orElse func() (O, error)) (O, error) {
if value.isSet {
return fn(value.value)
}
return orElse()
}
// Monad properties
func …
```
> test: zero value behaviour of Option

- backend/apps/test/samples/ab-events/jobs.fs
- backend/apps/test/samples/abcd-events/context.fs
- backend/apps/test/samples/abcd-events/jobs.fs
- backend/apps/test/samples/oauth/msgraph/msgraph.fs
- backend/apps/test/samples/oauth/spotify/spotify.fs
- backend/apps/test/test.fsproj
- backend/libraries/absample/absample.fsproj
- backend/libraries/ballerina-core/ballerina-core.fsproj
- backend/libraries/ballerina-core/business rule engine/expr/eval.fs
- backend/libraries/ballerina-core/business rule engine/expr/execute.fs
- backend/libraries/ballerina-core/business rule engine/expr/model.fs
- backend/libraries/ballerina-core/business rule engine/exprtype/typeCheck.fs
- backend/libraries/ballerina-core/business rule engine/exprtype/unification.fs
- backend/libraries/ballerina-core/business rule engine/form engine/parser/patterns.fs
- backend/libraries/ballerina-core/business rule engine/form engine/parser/renderers.fs
- backend/libraries/ballerina-core/business rule engine/form engine/parser/runner.fs
- backend/libraries/ballerina-core/business rule engine/form engine/validator.fs
- backend/libraries/ballerina-core/business rule engine/rule/execute.fs
- backend/libraries/ballerina-core/business rule engine/rule/variableRestrictionPredicate.fs
- backend/libraries/ballerina-core/collections/non-empty list/model.fs
- backend/libraries/ballerina-core/coroutine/model.fs
- backend/libraries/ballerina-core/state/model.fs
- backend/libraries/ballerina-core/state/with error/model.fs
- backend/libraries/ballerina-core/state/with error/seq/model.fs
- backend/libraries/oauth2/oauth2.fsproj
- backend/libraries/positions/positions.fsproj
- backend/libraries/users/model.fs
- backend/libraries/users/users.fsproj
Source: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options#opt-in-warnings
There is more to activate
> refactor: stricter compiler settings

- backend/libraries/ballerina-core/state/with error/model.fs
The function comes first. I didn't change the integration with the computational expressions, just the core monad
> fix: swap state bind arguments

- backend/libraries/ballerina-core/ballerina-core.fsproj
- backend/libraries/ballerina-core/packages.lock.json
This PR syncs changes from unbound repository tag 0.0.17
> chore: Sync from unbound 0.0.17

- backend/apps/ballerina-core.Tests/BusinessRuleEngine/Parser/Expr.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/ExprType/Patterns.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/FormEngine/Parser/Renderers.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Parser/Expr.fs
This PR syncs changes from unbound repository tag 0.0.19
> chore: Sync from unbound 0.0.19

- backend/apps/ballerina-core.Tests/ballerina-core.Tests.fsproj
- backend/apps/ballerina-core.Tests/packages.lock.json
This PR syncs changes from unbound repository tag 0.0.21
> chore: Sync from unbound 0.0.21

- backend/apps/ballerina-core.Tests/BusinessRuleEngine/Expr/Model.fs
- backend/apps/ballerina-core.Tests/BusinessRuleEngine/ExprType/TypeCheck.fs
- backend/apps/ballerina-core.Tests/BusinessRuleEngine/Parser/ExprType.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Expr/Eval.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Expr/Extension.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Expr/Model.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Expr/Patterns.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/ExprType/Model.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/ExprType/Patterns.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/ExprType/TypeCheck.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/ExprType/Unification.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/FormEngine/Model.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/FormEngine/Parser/FormsPatterns.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/FormEngine/Parser/Renderers.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/FormEngine/Parser/Runner.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/FormEngine/Validator.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Parser/Expr.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Parser/ExprType.fs
- backend/libraries/ballerina-core/BusinessRuleEngine/Parser/Patterns.fs
- backend/libraries/ballerina-core/Coroutine/Model.fs
- backend/libraries/ballerina-core/ballerina-core.fsproj
This PR syncs changes from unbound repository tag 0.0.22
> chore: Sync from unbound 0.0.22

- backend/apps/ballerina-lang.Tests/Parser/Expr.fs
This PR syncs changes from unbound repository tag 0.0.36
> chore: Sync from unbound 0.0.36

- backend/apps/ballerina-cat.Tests/ballerina-cat.Tests.fsproj
- backend/apps/ballerina-cat.Tests/packages.lock.json
- backend/apps/ballerina-lang.Tests/ExprType/TypeCheck.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Eval.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Unify.fs
- backend/apps/ballerina-lang.Tests/ballerina-lang.Tests.fsproj
- backend/apps/ballerina-lang.Tests/packages.lock.json
- backend/apps/ballerina-stdlib.Tests/ballerina-stdlib.Tests.fsproj
- backend/apps/ballerina-stdlib.Tests/packages.lock.json
- backend/libraries/ballerina-cat/Reader/WithError/Model.fs
- backend/libraries/ballerina-forms/ballerina-forms.fsproj
- backend/libraries/ballerina-forms/packages.lock.json
- backend/libraries/ballerina-lang/ExprType/Next/Next.fs
- backend/libraries/ballerina-lang/ExprType/Next/Unification.fs
- backend/libraries/ballerina-lang/ExprType/TypeCheck.fs
- backend/libraries/ballerina-lang/Extensions/Collections/Model.fs
- backend/libraries/ballerina-lang/Extensions/Primitives/Model.fs
- backend/libraries/ballerina-lang/packages.lock.json
- backend/libraries/ballerina-stdlib/Core/Map/Model.fs
- backend/libraries/ballerina-stdlib/ballerina-stdlib.fsproj
- backend/libraries/ballerina-stdlib/packages.lock.json
This PR syncs changes from unbound repository tag 0.0.38
> chore: Sync from unbound 0.0.38

- backend/apps/ballerina-lang.Tests/Expr/Model.fs
- backend/apps/ballerina-lang.Tests/ExprType/TypeCheck.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Eval.fs
- backend/apps/ballerina-lang.Tests/Next/Type/KindCheck.fs
- backend/apps/ballerina-lang.Tests/Parser/Expr.fs
- backend/apps/ballerina-lang.Tests/ballerina-lang.Tests.fsproj
- backend/apps/ballerina-lang.Tests/packages.lock.json
- backend/libraries/ballerina-forms/Parser/Runner.fs
- backend/libraries/ballerina-lang/ExprType/Next/Next.fs
- backend/libraries/ballerina-lang/Extensions/Collections/Model.fs
- backend/libraries/ballerina-lang/Extensions/Primitives/Model.fs
This PR syncs changes from unbound repository tag 0.0.41
> chore: Sync from unbound 0.0.41

- frontend/libraries/ballerina-core/src/forms/domains/dispatched-forms/runner/domains/abstract-renderers/readOnly/template.tsx
Introduces a check to ensure values are read-only, providing error handling and clear messaging when invalid values are encountered.
> Adds validation for read-only values

- backend/apps/ballerina-lang.Tests/Parser/ExprType.fs
- backend/libraries/ballerina-forms/Model.fs
- backend/libraries/ballerina-forms/Parser/FormsPatterns.fs
- backend/libraries/ballerina-forms/Parser/Renderers.fs
- backend/libraries/ballerina-forms/Validator.fs
- backend/libraries/ballerina-lang/Expr/Model.fs
- backend/libraries/ballerina-lang/ExprType/Model.fs
- backend/libraries/ballerina-lang/ExprType/Unification.fs
- backend/libraries/ballerina-lang/Parser/ExprType.fs
This PR syncs changes from unbound repository tag 0.0.43
> chore: Sync from unbound 0.0.43

- backend/libraries/ballerina-core-go/many.go
Implements the Many struct for managing linked and unlinked items with delta support.
- Adds Many struct with LinkedItems, UnlinkedItems, and AllItems fields
- Includes functions for mapping, default initialization, and delta operations
- Introduces DeltaMany struct and matching function for handling different delta types
- Provides constructors for creating delta instances with specific changes
This implementation enhances data collection management and enables efficient change tracking for linked and unlinked items.
> feat: Add Many struct

- backend/libraries/ballerina-core-go/ballerina_test/delta_option_test.go
- backend/libraries/ballerina-core-go/delta_option.go
Reverts Ballerina-Org/ballerina#390
> Revert "fix match option replace"

- backend/apps/ballerina-lang.Tests/Next/Type/Json/Type_TypeExpr.fs
- backend/libraries/ballerina-forms/Validator.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/AutomaticSymbolCreation.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/Record.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/Union.fs
- backend/libraries/ballerina-lang/ballerina-lang.fsproj
This PR syncs changes from unbound repository tag 0.0.74
> chore: Sync from unbound 0.0.74

- backend/apps/ballerina-lang.Tests/Next/Term/Expr_Eval.fs
- backend/apps/ballerina-lang.Tests/Next/Term/Json/Expr_TypeExpr.fs
- backend/apps/ballerina-lang.Tests/Next/Type/TypeCheck.fs
- backend/libraries/ballerina-cat/Collections/NonEmptyList/Model.fs
- backend/libraries/ballerina-cat/Parser/Model.fs
- backend/libraries/ballerina-forms/Model.fs
- backend/libraries/ballerina-forms/Parser/FormsPatterns.fs
- backend/libraries/ballerina-forms/Parser/Renderers.fs
- backend/libraries/ballerina-forms/Parser/Runner.fs
- backend/libraries/ballerina-forms/Validator.fs
- backend/libraries/ballerina-lang/Next/Json/Terms/Expr/Model.fs
- backend/libraries/ballerina-lang/Next/Json/Terms/Expr/UnionDes.fs
- backend/libraries/ballerina-lang/Next/Terms/Expr_Eval.fs
- backend/libraries/ballerina-lang/Next/Terms/Expr_TypeEval.fs
- backend/libraries/ballerina-lang/Next/Terms/Model.fs
- backend/libraries/ballerina-lang/Next/Terms/Patterns.fs
- backend/libraries/ballerina-lang/Next/Terms/TypeCheck.fs
- backend/libraries/ballerina-lang/Parser/ExprType.fs
This PR syncs changes from unbound repository tag 0.0.87
> chore: Sync from unbound 0.0.87

- backend/libraries/ballerina-forms/Model.fs
- backend/libraries/ballerina-forms/Parser/Runner.fs
- backend/libraries/ballerina-forms/Validator.fs
This PR syncs changes from unbound repository tag 0.0.93
> chore: Sync from unbound 0.0.93

- backend/libraries/ballerina-core-go/ballerina_test/delta_lazy_test.go
- backend/libraries/ballerina-core-go/delta_lazy.go
- backend/libraries/ballerina-core-go/lazy.go
@finite-automaton This defines the syntax for Lazy and DeltaLazy
> feat: separate lazy and one (part 1, create Lazy)

- backend/apps/ballerina-data.Tests/Delta/Record.fs
- backend/apps/ballerina-data.Tests/Delta/Union.fs
- backend/apps/ballerina-data.Tests/Schema/Eval.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Eval.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Json/Type_TypeExpr.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Json/Type_TypeValue.fs
- backend/apps/ballerina-lang.Tests/Next/Type/TypeCheck.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Unify.fs
- backend/apps/ballerina-stdlib.Tests/Core/OrderedMap.fs
- backend/libraries/ballerina-data/Delta/ToUpdater.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/AutomaticSymbolCreation.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/Model.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeValue/Record.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeValue/Union.fs
- backend/libraries/ballerina-lang/Next/Models/TypePatterns.fs
- backend/libraries/ballerina-lang/Next/Models/Types.fs
- backend/libraries/ballerina-lang/Next/Stdlib/Extensions/Types.fs
- backend/libraries/ballerina-lang/Next/TypeChecker/TypeCheck.fs
- backend/libraries/ballerina-lang/Next/TypeChecker/TypeEval.fs
- backend/libraries/ballerina-lang/Next/TypeChecker/Unification/Unification.fs
- backend/libraries/ballerina-seeds/Traverser.fs
- backend/libraries/ballerina-stdlib/Core/OrderedMap/Model.fs
- backend/libraries/ballerina-stdlib/Errors/Model.fs
This PR syncs changes from unbound repository tag 0.0.100
> chore: Sync from unbound 0.0.100

- backend/apps/ballerina-lang.Tests/Next/Integration.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Eval.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Json/Type_TypeExpr.fs
- backend/apps/ballerina-lang.Tests/Next/Type/TypeCheck.fs
- backend/apps/ballerina-lang.Tests/Next/Type/Unify.fs
- backend/libraries/ballerina-cat/Parser/Model.fs
- backend/libraries/ballerina-lang/Next/Eval/Expr_Eval.fs
- backend/libraries/ballerina-lang/Next/Eval/Expr_TypeEval.fs
- backend/libraries/ballerina-lang/Next/Json/Terms/Expr/Model.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/AutomaticSymbolCreation.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/Model.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/Record.fs
- backend/libraries/ballerina-lang/Next/Json/Types/TypeExpr/Union.fs
- backend/libraries/ballerina-lang/Next/Models/TermPatterns.fs
- backend/libraries/ballerina-lang/Next/Models/Terms.fs
- backend/libraries/ballerina-lang/Next/Models/Types.fs
- backend/libraries/ballerina-lang/Next/Stdlib/Extensions/Types.fs
- backend/libraries/ballerina-lang/Next/Syntax/Parser/Common.fs
- backend/libraries/ballerina-lang/Next/Syntax/Parser/Expr.fs
- backend/libraries/ballerina-lang/Next/TypeChecker/TypeCheck.fs
- backend/libraries/ballerina-lang/Next/TypeChecker/TypeEval.fs
- backend/libraries/ballerina-lang/Next/TypeChecker/Unification/Unification.fs
This PR syncs changes from unbound repository tag 0.0.105
> chore: Sync from unbound 0.0.105
